name: Add Video
description: Create an video tutorial.
title: 'Enter title here'
labels: []
body:
    - type: textarea
      id: description-textarea
      attributes:
          label: Description
          description: Tell us about this video.
          placeholder: Enter text
      validations:
          required: true
    - type: input
      id: source-input
      attributes:
          label: Video Source
          description: Enter your hosted video url
          placeholder: Enter url
      validations:
          required: true
    - type: input
      id: poster-input
      attributes:
          label: Video Poster
          description: Enter your hosted video poster
          placeholder: Enter img url
      validations:
          required: true
    - type: input
      id: duration-input
      attributes:
          label: Video Duration
          description: Enter your hosted video duration
          placeholder: Enter duration
      validations:
          required: true
